#!/usr/bin/env bash
# Rerun missing trials — generated by audit
# Usage: bash scripts/rerun_missing.sh 2>&1 | tee logs/rerun_missing_$(date +%Y%m%d).log
# Total missing: 24

set -euo pipefail
cd "/mnt/c/Users/afbla/Documents/Imperial/final_project"

python3 harness/run_trial.py --model "deepinfra/Qwen/Qwen3-VL-30B-A3B-Instruct" --task 0 --map ast --rep 1 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/Qwen/Qwen3-VL-30B-A3B-Instruct" --task 0 --map ast --rep 4 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/Qwen/Qwen3-VL-30B-A3B-Instruct" --task 4 --map ast --rep 1 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/Qwen/Qwen3-VL-30B-A3B-Instruct" --task 4 --map ast --rep 2 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/Qwen/Qwen3-VL-30B-A3B-Instruct" --task 4 --map ast --rep 4 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/Qwen/Qwen3-VL-30B-A3B-Instruct" --task 12 --map none --rep 4 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/Qwen/Qwen3-VL-30B-A3B-Instruct" --task 12 --map ast --rep 3 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/Qwen/Qwen3-VL-30B-A3B-Instruct" --task 14 --map none --rep 0 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/Qwen/Qwen3-VL-30B-A3B-Instruct" --task 14 --map none --rep 2 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/Qwen/Qwen3-VL-30B-A3B-Instruct" --task 14 --map none --rep 3 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/Qwen/Qwen3-VL-30B-A3B-Instruct" --task 15 --map ast --rep 2 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/Qwen/Qwen3-VL-30B-A3B-Instruct" --task 15 --map ast --rep 3 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/Qwen/Qwen3-VL-30B-A3B-Instruct" --task 15 --map ast_compact --rep 0 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/nvidia/Nemotron-3-Nano-30B-A3B" --task 14 --map none --rep 1 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/nvidia/Nemotron-3-Nano-30B-A3B" --task 14 --map none --rep 2 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/nvidia/Nemotron-3-Nano-30B-A3B" --task 14 --map ast --rep 0 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/nvidia/Nemotron-3-Nano-30B-A3B" --task 14 --map ast --rep 1 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/nvidia/Nemotron-3-Nano-30B-A3B" --task 14 --map ast --rep 4 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/nvidia/Nemotron-3-Nano-30B-A3B" --task 14 --map ast_compact --rep 3 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/nvidia/NVIDIA-Nemotron-3-Super-120B-A12B" --task 12 --map none --rep 2 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/nvidia/NVIDIA-Nemotron-3-Super-120B-A12B" --task 14 --map ast_compact --rep 3 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/zai-org/GLM-4.7-Flash" --task 4 --map none --rep 4 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/zai-org/GLM-4.7-Flash" --task 4 --map ast --rep 1 --max-turns 20
sleep 2
python3 harness/run_trial.py --model "deepinfra/zai-org/GLM-4.7-Flash" --task 14 --map none --rep 2 --max-turns 20
